DROP SEQUENCE UsersSeq;
DROP SEQUENCE GameSeq;
DROP SEQUENCE PersonSeq;
DROP SEQUENCE PublisherSeq;
DROP SEQUENCE TagSeq;
DROP TABLE GameTag;
DROP TABLE Tag;
DROP TABLE GameArtist;
DROP TABLE GamePublisher;
DROP TABLE Publisher;
DROP TABLE Rating;
DROP TABLE Game;
DROP TABLE Person;
DROP TABLE Users;

