CREATE TABLE Users ( id NUMBER(6) NOT NULL PRIMARY KEY,
	login VARCHAR2(100) NOT NULL UNIQUE,
	pass VARCHAR2(32) NOT NULL);

CREATE TABLE Person (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE);

CREATE TABLE Game (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE,
	year NUMBER(4) NOT NULL,
	description VARCHAR2(2000) NOT NULL,
	bggscore NUMBER(4,2) NOT NULL,
	designerid NUMBER(6) NOT NULL REFERENCES Person,
	minplayers NUMBER(2) NOT NULL,
	maxplayers NUMBER(2) NOT NULL,
	avgplaytime NUMBER(4) NOT NULL,
	complexity NUMBER(3,2) NOT NULL);

CREATE TABLE Rating (
	value NUMBER(2) NOT NULL,
	userid NUMBER(6) NOT NULL REFERENCES Users,
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	PRIMARY KEY (value, userid));	

CREATE TABLE Publisher (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE);

CREATE TABLE GamePublisher (
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	publisherid NUMBER(6) NOT NULL REFERENCES Publisher,
	PRIMARY KEY (gameid, publisherid));

CREATE TABLE GameArtist (
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	artistid NUMBER(6) NOT NULL REFERENCES Person,
	PRIMARY KEY (gameid, artistid));

CREATE TABLE Category (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE);

CREATE TABLE Mechanism (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE);

CREATE TABLE Family (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE);

CREATE TABLE Types (
	id NUMBER(6) NOT NULL PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE);

CREATE TABLE GameCategory (
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	categoryid NUMBER(6) NOT NULL REFERENCES Category,
	PRIMARY KEY (gameid, categoryid));

CREATE TABLE GameMechanism (
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	mechanismid  NUMBER(6) NOT NULL REFERENCES Category,
	PRIMARY KEY (gameid, mechanismid));

CREATE TABLE GameFamily (
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	familyid NUMBER(6) NOT NULL REFERENCES Category,
	PRIMARY KEY (gameid, familyid));

CREATE TABLE GameType (
	gameid NUMBER(6) NOT NULL REFERENCES Game,
	typeid NUMBER(6) NOT NULL REFERENCES Types,
	PRIMARY KEY (gameid, typeid));	
