CREATE SEQUENCE UsersSeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER users_in_trigger
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
	SELECT UsersSeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE GameSeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER game_in_trigger
BEFORE INSERT ON Game
FOR EACH ROW
BEGIN
	SELECT GameSeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE PersonSeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER person_in_trigger
BEFORE INSERT ON Person
FOR EACH ROW
BEGIN
	SELECT PersonSeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE PublisherSeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER publisher_in_trigger
BEFORE INSERT ON Publisher
FOR EACH ROW
BEGIN
	SELECT PublisherSeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE CategorySeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER category_in_trigger
BEFORE INSERT ON Category
FOR EACH ROW
BEGIN
	SELECT CategorySeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE MechanismSeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER mechanism_in_trigger
BEFORE INSERT ON Mechanism
FOR EACH ROW
BEGIN
	SELECT MechanismSeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE FamilySeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER family_in_trigger
BEFORE INSERT ON Family
FOR EACH ROW
BEGIN
	SELECT FamilySeq.nextval INTO :NEW.id FROM dual;
END;
/

CREATE SEQUENCE TypesSeq START WITH 1 INCREMENT BY 1;
CREATE TRIGGER types_in_trigger
BEFORE INSERT ON Types
FOR EACH ROW
BEGIN
	SELECT TypesSeq.nextval INTO :NEW.id FROM dual;
END;
/
